apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  selector:
    matchLabels:
      app: slackbot-pod
  replicas: 2
  template:
    metadata:
      name: slackbot-pod
      labels:
        app: slackbot-pod
    spec:
      containers:
        - name: slackbot
          image: vader404/slackbot:v2.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: slackbot-config-map
            - secretRef:
                name: slackbot-secret