apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  # Add labels and annotations as per your requirements
spec:
  selector:
    app: rabbitmq
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672